#!/bin/bash

branch="$1"
parentsFile="$(git rev-parse --git-dir)/branch-parents"

if [ -f "$parentsFile" ]; then
  parentBranch=$(grep "$branch:" "$parentsFile" | head -1 | sed "s|$branch:||")
  if [ ! -z "$parentBranch" ]; then
    echo "$parentBranch"
  else
    exit 1
  fi
else
  exit 1
fi

# | sed -n "s|$1:||p" | head -1)
# if [ -f "$parentsFile" ]; then
#   if grep -q "$branch:.*" "$parentsFile"; then
#     parentBranch=$(grep "$branch:.*" "$parentsFile" | sed "s|$branch:||" | head -1)
#     if [ ! -z "$parentBranch" ]; then
#       echo "$parentBranch"
#     else
#       exit 1
#     fi
#   else
#     exit 1
#   fi
# else
#   exit 1
# fi

# exit 0
