#!/bin/bash

branch="$1"
parentBranch="$2"
parentsFile="$(git rev-parse --git-dir)/branch-parents"
getParent="$(git rev-parse --git-dir)/get-branch-parent"

if [ "$parentBranch" = "--remove" ]; then
  if "$getParent" "$branch" > /dev/null; then
    parentBranch=$("$getParent" "$branch")
    grep -v "$branch:.*" "$parentsFile" > "$parentsFile.new"; mv "$parentsFile.new" "$parentsFile"

    if [ $parentBranch = "--ignore" ]; then
      echo -e "Branch \e[1m\e[32m$branch\e[0m is no longer being ignored."
    else
      echo -e "The parent of branch \e[1m\e[32m$branch\e[0m is no longer set to \e[1m\e[32m$parentBranch\e[0m."
    fi
  else
    echo -e "There isn't any parent set for branch \e[1m\e[32m$branch\e[0m."
  fi
else
  if [ "$branch" = "$parentBranch" ]; then
    echo -e "Branch \e[1m\e[32m$branch\e[0m cannot be its own parent." >&2
    exit 1
  fi
  if [ "$("$getParent" "$parentBranch")" = "--ignore" ]; then
    echo -e "Branch \e[1m\e[32m$parentBranch\e[0m is being ignored." >&2
    exit 1
  fi

  counter=20
  originalParent=$parentBranch
  while "$getParent" "$parentBranch" > /dev/null && [ "$("$getParent" "$parentBranch")" != "--ignore" ]; do
    parentBranch="$("$getParent" "$parentBranch")"
    counter=$(($counter - 1))
    if [ "$branch" = "$parentBranch" -o $counter -lt 0 ]; then
      echo -e "The parent of branch \e[1m\e[32m$branch\e[0m cannot be \e[1m\e[32m$originalParent\e[0m since that would result in an infinite loop." >&2
      exit 1
    fi
  done
  parentBranch=$originalParent

  if "$getParent" "$branch" > /dev/null; then
    sed "s|$branch:.*|$branch:$parentBranch|g" "$parentsFile" > "$parentsFile.new" && mv "$parentsFile.new" "$parentsFile"
  else
    echo "$branch:$parentBranch" >> "$parentsFile"
  fi

  if [ "$parentBranch" = "--ignore" ]; then
    echo -e "Branch \e[1m\e[32m$branch\e[0m is now being ignored. It won't be tagged, and it won't be added to other branches' tags."
  else
    echo -e "The parent of branch \e[1m\e[32m$branch\e[0m has been set to \e[1m\e[32m$parentBranch\e[0m."
  fi
fi

exit 0
