#!/bin/bash

# $1 = branch

parentsFile="$(git rev-parse --git-dir)/commit-tagger.parents"
ignoredFile="$(git rev-parse --git-dir)/commit-tagger.ignored"
parents="$(cat "$parentsFile" 2> /dev/null)"
ignored="$(cat "$ignoredFile" 2> /dev/null)"

parent=$(printf "$parents" | grep "^$1:" | head -1 | sed "s|^$1:||")

function isIgnored {
  # $1 = branch
  printf "$ignored" | grep -q "^$1$"
  return $?
}

if [ -n "$parent" ]; then
  printf "The parent of branch \e[1m$1\e[0m is \e[1m$parent\e[0m.\n"
  if isIgnored "$1"; then
    printf "Branch \e[1m$1\e[0m is being ignored.\n"
  fi
  if isIgnored "$parent"; then
    printf "Branch \e[1m$parent\e[0m is being ignored.\n"
  fi
  exit 0
else
  printf "Branch \e[1m$1\e[0m does not have a parent.\n"
  if isIgnored "$1"; then
    printf "Branch \e[1m$1\e[0m is being ignored.\n"
  fi
  exit 1
fi
