#!/bin/bash

# $1 = branch

parentsFile="$(git rev-parse --git-dir)/commit-tagger.parents"
ignoredFile="$(git rev-parse --git-dir)/commit-tagger.ignored"
parents="$(cat "$parentsFile" 2> /dev/null)"
ignored="$(cat "$ignoredFile" 2> /dev/null)"

function getParent {
  #$1 = branch
  local parent
  parent="$(printf "$parents" | sed -n "s|^$1:||p" | head -1)"
  if [ -n "$parent" ]; then
    printf "$parent"
    return 0
  else
    return 1
  fi
}

function isIgnored {
  # $1 = branch
  printf "$ignored" | grep -q "^$1$"
  return $?
}

parent="$(getParent "$1")"
if [ $? -eq 0 ]; then
  parents="$(grep -v "^$1:" "$parentsFile")"
  if [ -n "$parents" ]; then
    printf "$parents\n" > "$parentsFile"
  else
    printf "" > "$parentsFile"
  fi
  printf "Branch \e[1m$1\e[0m no longer has \e[1m$parent\e[0m set as parent.\n"
else
  printf "There isn't any parent set for branch \e[1m$1\e[0m.\n"
fi

if isIgnored "$1"; then
  printf "Branch \e[1m$1\e[0m is being ignored.\n"
fi

exit 0
