#!/bin/bash

# $@ = list of branches

ignoredFile="$(git rev-parse --git-dir)/commit-tagger.ignored"
ignored="$(cat "$ignoredFile" 2> /dev/null)"

function isIgnored {
  # $1 = branch
  printf "$ignored" | grep -q "^$1$"
  return $?
}

for branch in "$@"; do
  if isIgnored "$branch"; then
    ignored="$(grep -v "^$branch$" "$ignoredFile")"
    if [ -n "$ignored" ]; then
      printf "$ignored\n" > "$ignoredFile"
    else
      printf "" > "$ignoredFile"
    fi
    printf "Branch \e[1m$branch\e[0m is no longer being ignored.\n"
  else
    printf "Branch \e[1m$branch\e[0m is not currently beign ignored.\n"
  fi
done

exit 0
